### ISSUE TITLE
svOnStart errors.

### ISSUE THREAD

**Issue by dmackerman** [kamilkp/angular-sortable-view#38] opened 2015-04-27 20:27 UTC
Angular doesn't like binding DOM nodes to expressions.
https://docs.angularjs.org/error/$parse/isecdom?p0=journey.onTaskDrag($item,%20$part,%20$index,%20$helper

**Comment by kamilkp** [comment] 2015-04-27 21:01
Isn't it a duplicate of #12 ?

**Comment by dmackerman** [comment] 2015-04-28 12:38
Ah, yes. Sorry!

Another question - would there be a way to access the `$helper` inside a directive instead? I want to add and remove classes, but doing so in a controller feels wrong.

**Comment by lookfirst** [comment] 2015-09-08 23:51
Ugh... @kamilkp when will you fix this?

**Closed** 2022-02-25 18:12 UTC
